apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 9-169-76-123.sslip.io       # replace with your FQDN or remove for IP-based
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service   # must match ClusterIP service name
                port:
                  number: 80